/***************************************************************************//**
 * @file  zap-enabled-incoming-commands.h
 * @brief This file contains a set of macros for all the cluster commands which
 have incoming enabled.
 * This file is generated. Do not update file manually.
 *******************************************************************************
 * # License
 * <b>Copyright 2020 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/
#define ZCL_CLUSTER_BASIC_SERVER_INCOMING_COMMAND_RESET_TO_FACTORY_DEFAULTS_ENABLED
#define ZCL_CLUSTER_GROUPS_CLIENT_INCOMING_COMMAND_ADD_GROUP_RESPONSE_ENABLED
#define ZCL_CLUSTER_GROUPS_CLIENT_INCOMING_COMMAND_VIEW_GROUP_RESPONSE_ENABLED
#define ZCL_CLUSTER_GROUPS_CLIENT_INCOMING_COMMAND_GET_GROUP_MEMBERSHIP_RESPONSE_ENABLED
#define ZCL_CLUSTER_GROUPS_CLIENT_INCOMING_COMMAND_REMOVE_GROUP_RESPONSE_ENABLED
#define ZCL_CLUSTER_IDENTIFY_CLIENT_INCOMING_COMMAND_IDENTIFY_QUERY_RESPONSE_ENABLED
#define ZCL_CLUSTER_IDENTIFY_SERVER_INCOMING_COMMAND_IDENTIFY_ENABLED
#define ZCL_CLUSTER_IDENTIFY_SERVER_INCOMING_COMMAND_IDENTIFY_QUERY_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_ADD_SCENE_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_VIEW_SCENE_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_REMOVE_SCENE_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_REMOVE_ALL_SCENES_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_STORE_SCENE_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_GET_SCENE_MEMBERSHIP_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_ENHANCED_ADD_SCENE_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_ENHANCED_VIEW_SCENE_RESPONSE_ENABLED
#define ZCL_CLUSTER_SCENES_CLIENT_INCOMING_COMMAND_COPY_SCENE_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_SCAN_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_DEVICE_INFORMATION_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_NETWORK_START_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_NETWORK_JOIN_ROUTER_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_NETWORK_JOIN_END_DEVICE_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_ENDPOINT_INFORMATION_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_GET_GROUP_IDENTIFIERS_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_CLIENT_INCOMING_COMMAND_GET_ENDPOINT_LIST_RESPONSE_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_SCAN_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_DEVICE_INFORMATION_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_IDENTIFY_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_RESET_TO_FACTORY_NEW_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_START_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_JOIN_ROUTER_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_JOIN_END_DEVICE_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_NETWORK_UPDATE_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_GET_GROUP_IDENTIFIERS_REQUEST_ENABLED
#define ZCL_CLUSTER_ZLL_COMMISSIONING_SERVER_INCOMING_COMMAND_GET_ENDPOINT_LIST_REQUEST_ENABLED
